export const queryKeys = {
  restaurant: ['restaurant'] as const,
  categories: ['categories'] as const,
  menuItems: (params?: Record<string, unknown>) => ['menu-items', params ?? {}] as const,
  customerOrders: ['customer', 'orders'] as const,
  customerOrder: (id: string | number | undefined) => ['customer', 'orders', id] as const,
  customerAddresses: ['customer', 'addresses'] as const,
  devices: ['devices'] as const,
  riderDeliveries: ['rider', 'deliveries'] as const,
  riderDelivery: (id: string | number | undefined) => ['rider', 'deliveries', id] as const,
  riderHistory: ['rider', 'deliveries', 'history'] as const,
  riderDashboard: ['rider', 'dashboard'] as const,
  adminDashboard: ['admin', 'dashboard'] as const,
  adminRestaurant: ['admin', 'restaurant'] as const,
  adminCategories: ['admin', 'categories'] as const,
  adminMenuItems: (params?: Record<string, unknown>) => ['admin', 'menu-items', params ?? {}] as const,
  adminMenuItem: (id: string | number | undefined) => ['admin', 'menu-items', id] as const,
  adminOrders: (params?: Record<string, unknown>) => ['admin', 'orders', params ?? {}] as const,
  adminOrder: (id: string | number | undefined) => ['admin', 'orders', id] as const,
  adminRiders: ['admin', 'riders'] as const,
  adminRider: (id: string | number | undefined) => ['admin', 'riders', id] as const,
  health: ['health'] as const,
};
