export const endpoints = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    logout: '/auth/logout',
    passwordOtp: '/auth/password/otp',
    passwordOtpVerify: '/auth/password/otp/verify',
    passwordReset: '/auth/password/reset',
  },
  restaurant: '/restaurant',
  categories: '/categories',
  menuItems: '/menu-items',
  customer: {
    profile: '/customer/profile',
    addresses: '/customer/addresses',
    cart: '/customer/cart',
    orders: '/customer/orders',
    checkout: '/customer/checkout',
  },
  devices: '/devices',
  rider: {
    dashboard: '/rider/dashboard',
    deliveries: '/rider/deliveries',
    deliveryHistory: '/rider/deliveries/history',
    location: '/rider/location',
    profile: '/rider/profile',
  },
  admin: {
    dashboard: '/admin/dashboard',
    orders: '/admin/orders',
    riders: '/admin/riders',
    categories: '/admin/categories',
    menuItems: '/admin/menu-items',
    restaurant: '/admin/restaurant',
  },
} as const;
